### ISSUE TITLE
Service won't start (pfsense)

### ISSUE THREAD

**Issue by Obeja** [synfinatic/udp-proxy-2020#101]
I'm a complete novice in pfsense/fresbsd but quite an old user of Roon. Udp-proxy-2020 has solved a problem I wished it was addressed so long ago by Roon  themselves. And for that I really appreciate your work and thank you for this project.
I followed the startup script for pfsense and kinda made ir work. I'm in version 2.6.0 of pfsense. 

I get this error when starting the service (Checked several times the file content and locations but no change in error) :
[admin@pfSense]/root: service udp-proxy-2020 start
/usr/local/etc/udp-proxy-2020.conf: udp-proxy-2020: not found

After several attempts I tried the direct way and worked (same instructions present in the conf file):

[admin@pfSense]/root: udp-proxy-2020 --port 9003 --interface bridge0,tun_wg0 --cache-ttl 300

I assume the problem is caused by something I'm missing but would not recognize the issue even if stared at me. I assume because of this error, auto-start on boot won't work. I would really appreciate you help.

I also get this warning messages every few minutes of music streaming:

WARNING Unable to send 130 bytes from bridge0 out tun_wg0: send: Address family not supported by protocol family 
WARNING Unable to send 130 bytes from bridge0 out tun_wg0: send: Address family not supported by protocol family 
WARNING Unable to send 130 bytes from bridge0 out tun_wg0: send: Address family not supported by protocol family

Are this alerts of any concern?

Thanks in advance.

**Comment by synfinatic** [comment]
the warnings aren't an issue.  I see the same thing on pfSense with Wireguard.  just has to do with some other packets Roon sends that aren't important in this config.

`service udp-proxy-2020 start` not working seems like you have something misconfigured but you didn't provide enough information for me to guess why.  I'd re-read the installation instructions and ensure you've done each step correctly.  

Sorry, I can't make the startup scripts easier... FreeBSD/pfSense packaging is a bit of a mess and I don't have the time to dig deeper to figure it out.

**Comment by Obeja** [comment]
Figured out what was happening. Now running with no issues. Thanks for your quick reply.
