### ISSUE TITLE
Could you please explain how to use docker

### ISSUE THREAD

**Issue by invoker-karl** [synfinatic/udp-proxy-2020#102]
Could you please explain how to use docker

**Comment by synfinatic** [comment]
need to use host networking.

**Comment by invoker-karl** [comment]
Hello，i use host networking。   
 It is my conmand:
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='udp-proxy-2020' --net='host' --privileged=true -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="udp-proxy-2020" -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='interface=wg0' 'synfinatic/udp-proxy-2020'
0c65efb5aed7ad613280522de302fb13522241b3fe9e0925a8ed4177c3a911db

but my log in latter:
udp-proxy-2020: error: --interface: expected string value but got "--timeout" (long flag); perhaps try --interface="--timeout"?
Usage: udp-proxy-2020



could you help me? 
Thanks

**Comment by synfinatic** [comment]
If you look at the [Dockerfile](https://github.com/synfinatic/udp-proxy-2020/blob/main/Dockerfile) you'll see you need to specify some environment variables.  That's why you're getting the error.

**Comment by invoker-karl** [comment]
Thanks! i alrdly use!

**Comment by invoker-karl** [comment]
I am sorry to aks you twitws secend.      I alrdly already run docker in roon，that already listen port 9003.    When i run docker that port 9003 in udp-proxy-2020.  I have other issue.  
It is my log: level=fatal msg="Unable to init SinkUdpPackets" error="192.168.1.200:9003: listen udp4 192.168.1.200:9003: bind: address already in use"
So what can i do?
Thanks.

**Comment by synfinatic** [comment]
`EXTRA_ARGS=--no-listen`

**Comment by invoker-karl** [comment]
Thanks! It is working!
