### ISSUE TITLE
Config file not read

### ISSUE THREAD

**Issue by Draven0** [synfinatic/udp-proxy-2020#108]
I followed the instructions for setting this up on PFSense however i am using OPNSense which is pretty much the same thing. It works flawlessly if i run it in command line. However if i try to set it up as a service following the instructions on the read me. all i get is the help file and then 

udp-proxy-2020: error: unexpected argument start

udp-proxy-2020.conf
# change the port and add --interface {dev-name} as many times as needed.
udp_vars="--port 47584 --interface em0,ovpns2 --fixed-ip=ovpns2@10.10.10.0"

Any ideas, it is working brilliantly for what i want if i run it directly I just can't get the service to start properly.

**Comment by Draven0** [comment]
I copied the wrong file into each folder, i've got that bit right. now but when i type udp-proxy-2020 start it doesn't start just says is not running.

**Comment by synfinatic** [comment]
I assume you are typing `service udp-proxy-2020 start` ?

Have you looked in `/var/log/udp-proxy-2020.log` for any errors?

**Comment by Draven0** [comment]
if i type 

root@fw1:/var/log # service udp-proxy-2020 start
root@fw1:/var/log # service udp-proxy-2020 status
udp-proxy-2020 is not running.
root@fw1:/var/log # service udp-proxy-2020 stop
Unable to kill udp_proxy_2020.  Missing pid file?
root@fw1:/var/log #

**Comment by synfinatic** [comment]
does `/usr/local/bin/udp-proxy-2020` exist?  Is the binary executable?

**Comment by Draven0** [comment]
Oh, well umm. 

No, not it didn't.. now it does.. 

Can you tell i'm tired.. it's been a very long day

root@fw1:/usr/local/bin # service udp-proxy-2020 start
root@fw1:/usr/local/bin # service udp-proxy-2020 status
udp-proxy-2020 is running (783

Thank you for the ultra quick response and this is a brilliant bit of software solves a problem for me so very my appreciate your work.
