### ISSUE TITLE
Running over Docker macvlan interfaces

### ISSUE THREAD

**Issue by smangels** [synfinatic/udp-proxy-2020#111]
I wonder if it would be possible to run udp-proxy-20202 over Docker macvlan interfaces as well? I've managed to bring the Docker container up with 2 interfaces (fixed IP) using macvlan driver. My question is where to put the udp-proxy-2020 instance.

# Question
* Do I have to run the proxy instance inside the router where the wireguard tunnel from clients are terminated or could I run the proxy at the same machine where Roon is running?
* How to configure the UDP proxy located in the Raspberry PI (located in working location) - standard config or is this a special case.

# Network Setup
`Roon server -> macvlan -> [ router, GW -> wg1 -> wan ] -> internet -> [ raspberry, wifi -> wg0 ]`

## Server:
- Roon running inside a Docker container on multiple macvlan interfaces with fixed IP 10.60.201.10/24
- (proposal) setup udp-proxy with single interface and fixed IP listening on UDP/9003, 10.60.201.12/24

## Router (Mikrotik)
- running Wireguard-server 10.60.206.1
- acts as gateway for 10.60.201.0/24

## Raspberry Pi4 (remote instance in job location)
- running Roon Bridge
- running wireguard, assigned IP 10.60.206.100/32
- running udp-proxy (proposal 2 interfaces wlan0, wg1, --fixed-ip 10.60.201.12)

**Comment by synfinatic** [comment]
1. Roon has to run where the wireguard tunnel is.
 2. I don't have a recipe for site to site right now.... mostly because I don't have a network which makes it easy to support really.  
 3. `macvlan` support is ¯\\_(ツ)_/¯  as I have no idea and don't have time to test every possible configuration.  Try it and let me know. :)

**Comment by synfinatic** [comment]
Btw, are you using RoPieee on the Pi?  Because that doesn't use Roon's RAAT or discovery service.  It's AirPlay which is a different thing altogether and not something I've played with.  It's definitely not udp/9003 for example.

Anyways, will close this ticket soon if I don't here more from you.

**Comment by synfinatic** [comment]
closing as no further contact.
