### ISSUE TITLE
rename --listen and --promisc

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/udp-proxy-2020#12]
The existing flags are probably confusing for non-technical people.  In reality, they're more about what kind of interface you're using so it would be more like --ethernet and --loopback

**Comment by ilmanzo** [comment]
Hello, glad to contribute! Can I take this issue ?

**Comment by synfinatic** [comment]
So I've realized that this is something that should be fixed along with #5.   Basically use  the `Flags` in https://golang.org/pkg/net/#Interface to auto-detect if the interface supports broadcasts or not, so the goal would to have a single `--interface` flag and handle things automatically. 

FWIW, this is probably the next thing I was going to work on (once I'm done refactoring & cleaning up the Makefile/Dockerfiles) because this and #5 are blocking #6.

So yeah, if you want to send a PR that's great.

**Comment by ilmanzo** [comment]
Ok I'll give it a try :)
