### ISSUE TITLE
Running in a vm

### ISSUE THREAD

**Issue by theikid** [synfinatic/udp-proxy-2020#144]
Hi there,

i run my roon core on a linux vm on truenas scale.

when connecting using wireguard i cannot use my computer as an endpoint. The udp proxy seems the way yo go but i dont know if i should install it on the same vm of my roon server or maybe on my ubiquiti router ?

**Comment by synfinatic** [comment]
Not a lot of information, but yeah the router is probably the right choice.

**Comment by synfinatic** [comment]
oh, I don't think it will work on the gateway then.  You say you're using port-forwarding so you have a dedicated subnet for the VM's and are using NAT?  

Anyways, you will want udp-proxy-2020 to run on the same host as the wireguard server since it has to route traffic over the wireguard network.

**Comment by theikid** [comment]
> oh, I don't think it will work on the gateway then. You say you're using port-forwarding so you have a dedicated subnet for the VM's and are using NAT?
> 
> Anyways, you will want udp-proxy-2020 to run on the same host as the wireguard server since it has to route traffic over the wireguard network.

I'll move my wireguard from my truenas to my router then that should be better to let my router handle all network stuff. Thanks for your help, I'll report back asap.
