### ISSUE TITLE
Error when launching script

### ISSUE THREAD

**Issue by theikid** [synfinatic/udp-proxy-2020#146]
Hello there, I installed the script following that tutorial on Roon forum on my unifi router : 

https://community.roonlabs.com/t/how-to-roon-mobile-over-wireguard-on-a-unifi-usg/
When launching the script I got the following error : ./udp-proxy-2020: 1: Syntax error: "(" unexpected

Would you have any lead ?

**Comment by synfinatic** [comment]
can you provide exactly what you typed?

**Comment by theikid** [comment]
> can you provide exactly what you typed?

Sure i got the mips package from release page. Scp it through shh and put it in /bin/ folder renaming it to udp-proxy-2020.

i chown +x the file and did: sudo ./udp-proxy-2020 --port 9003 --interface eth1,wgsrv1

**Comment by synfinatic** [comment]
well the `udp-proxy-2020` is a compiled GoLang binary... so no idea how you got that kind of error which sounds more like it is from a shell script.   

What does the command `file udp-proxy-2020` output?

**Comment by theikid** [comment]
> well the `udp-proxy-2020` is a compiled GoLang binary... so no idea how you got that kind of error which sounds more like it is from a shell script.
> 
> What does the command `file udp-proxy-2020` output?

Sure 👍🏻 
"ELF 64-bit MSB executable, MIPS, MIPS64 rel2 version 1 (SYSV), statically linked, BuildID[sha1]=da9746d064e3a84d81ee9a8c9bc28122defcf868, for GNU/Linux 3.2.0, stripped"

**Comment by theikid** [comment]
@synfinatic I actually manage to make it work, architecture assumption was wrong as my ubiquity router user arm64 Debian and not mips apparently.

But now I've got the service to stop randomly. Here is systemd status :

● udp-proxy-2020.service - UDP Proxy 20202
     Loaded: loaded (/etc/systemd/system/udp-proxy-2020.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-02-01 09:07:05 CET; 13min ago
       Docs: https://github.com/synfinatic/udp-proxy-2020
    Process: 2075571 ExecStart=/usr/bin/udp-proxy-2020 $ARGS (code=exited, status=1/FAILURE)
   Main PID: 2075571 (code=exited, status=1/FAILURE)
        CPU: 67ms

Feb 01 09:07:05 Coruscant systemd[1]: udp-proxy-2020.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 09:07:05 Coruscant systemd[1]: udp-proxy-2020.service: Failed with result 'exit-code'.
Feb 01 09:07:05 Coruscant systemd[1]: udp-proxy-2020.service: Scheduled restart job, restart counter is at 5.
Feb 01 09:07:05 Coruscant systemd[1]: Stopped UDP Proxy 20202.
Feb 01 09:07:05 Coruscant systemd[1]: udp-proxy-2020.service: Start request repeated too quickly.
Feb 01 09:07:05 Coruscant systemd[1]: udp-proxy-2020.service: Failed with result 'exit-code'.
Feb 01 09:07:05 Coruscant systemd[1]: Failed to start UDP Proxy 20202.

**Comment by synfinatic** [comment]
Do you know Linux and systemd?  Need to use `journalctl` to view the logs.

my guess though is something is wrong with the config file.
