### ISSUE TITLE
Problems getting AirPlay to work

### ISSUE THREAD

**Issue by tiehfood** [synfinatic/udp-proxy-2020#148]
I'm trying to get an AirPlay Device working over a site-to-site Wireguard VPN connection. The mDNS packages are successfully replicated to the other network but the pairing process of AirPlay fails.

The Network-Setup in a simplified way looks like this:

NetA (192.168.100.0/24) <- WgTunnel -> NetB (192.168.200.0/24)
Roon (192.168.100.10)
AirPlayDevice (192.168.200.10)

This is the message I get from Roon:
```
02/10 21:46:10 Debug: start pin, url: http://192.168.100.1:7000/pair-pin-start
```

Somehow the IP Roon is trying to access during the initial pairing process is not the IP of the AirPlay Device but the IP of the Gateway (First Hop)....

**Comment by synfinatic** [comment]
Sorry, but I haven't done any testing / compatibility wit AirPlay.   No idea if it can work.
