### ISSUE TITLE
Add LinkType RAW support for Wireguard

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/udp-proxy-2020#29]

**Comment by synfinatic** [comment]
didn't work.  Wireguard is showing linktype = 12 ?

**Comment by fraf1** [comment]
As agreed

[wireguard.pcap.net_10_6_0_2.gz](https://github.com/synfinatic/udp-proxy-2020/files/5360657/wireguard.pcap.net_10_6_0_2.gz)

pcap file on port wg0 obtained with:
tcpdump -n -i wg0 -s0 -w wireguard.pcap.net_10_6_0_2 'net 10.6.0.2'

**Comment by fraf1** [comment]
New logs...
[logs.zip](https://github.com/synfinatic/udp-proxy-2020/files/5363178/logs.zip)

Thanks!

**Comment by synfinatic** [comment]
@fraf1 The logs you provided appear to be for an older version of code for the `wireguard` branch.  Can you try pulling the latest version?  If you get an error, you might need to do:

```
git fetch --all
git reset --hard origin/wireguard
```

Btw, you can tell if you have the correct version or not by looking at the output in the logs.  The old logs printed the packet as a list of decimal values.  The new code prints it as a hex string.

**Comment by fraf1** [comment]
Mmh...
It looks it is up to date now. It compiles into a binary with 0.0.5 in the name and git says there's nothing new:

```
root@rpi4:~/BUILD/udp-proxy-2020-git/udp-proxy-2020# git status
On branch wireguard
Your branch is up to date with 'origin/wireguard'.

nothing to commit, working tree clean
root@rpi4:~/BUILD/udp-proxy-2020-git/udp-proxy-2020# git pull
Already up to date.
```
But the execution now fails with:

```
time="2020-10-12T21:42:02+02:00" level=debug msg="handlePackets(wg0) ticker" func="main.(*Listen).handlePackets" file="/root/BUILD/udp-proxy-2020-git/udp-proxy-2020/cmd/listen.go:124"
time="2020-10-12T21:42:04+02:00" level=fatal msg="Unsupported source linktype: Raw" func="main.(*Listen).learnClientIP" file="/root/BUILD/udp-proxy-2020-git/udp-proxy-2020/cmd/listen.go:305"

```

Logs attached:
[logs_02.zip](https://github.com/synfinatic/udp-proxy-2020/files/5367191/logs_02.zip)

**Comment by fraf1** [comment]
For info, I tried to modify the code around line 305 with some extra output as:

```
	switch l.handle.LinkType() {
	case layers.LinkTypeNull:
		parser = gopacket.NewDecodingLayerParser(layers.LayerTypeLoopback, &loop, &ip4, &udp, &payload)
	case layers.LinkTypeLoop:
		parser = gopacket.NewDecodingLayerParser(layers.LayerTypeLoopback, &loop, &ip4, &udp, &payload)
	case layers.LinkTypeEthernet:
		parser = gopacket.NewDecodingLayerParser(layers.LayerTypeEthernet, &eth, &ip4, &udp, &payload)
	case layers.LinkTypeRaw:
		parser = gopacket.NewDecodingLayerParser(layers.LayerTypeIPv4, &ip4, &udp, &payload)
	default:
		log.Fatalf("Unsupported source linktype: %s. LinkTypeRaw is: %s", l.handle.LinkType(), layers.LinkTypeRaw)
	}
```

And the message I get is:

`FATA[0015]/root/BUILD/udp-proxy-2020-git/udp-proxy-2020/cmd/listen.go:305 main.(*Listen).learnClientIP() Unsupported source linktype: Raw. LinkTypeRaw is: Raw`

So both l.handle.LinkType() and layers.LinkTypeRaw print as "Raw", but they do not match in the case statement.

**Comment by synfinatic** [comment]
Ah, that's useful.  That's another case of Wireguard interfaces storing the string `Raw` where it should store the `101` value.  I just pushed another change which should hopefully work around that.

**Comment by fraf1** [comment]
Ok, it went on this time, with lots of messages in the console (even if Roon from VPN does not work yet...)

New logs attached!
[logs_03.zip](https://github.com/synfinatic/udp-proxy-2020/files/5367334/logs_03.zip)

**Comment by synfinatic** [comment]
Thanks, that was helpful.  going to have to dig into this deeper after work today.

**Comment by synfinatic** [comment]
So I don't see anything obviously wrong other than the UDP broadcasts from your phone (10.6.0.2) are not being replied to from the Roon Core.  Based on the logs, it appears your local network is 192.168.0.0/24 (your raspberrypi is 192.168.0.172)?  Is that the network your Roon Core is on?

Assuming your Roon core is on that network, I guess the next thing to do is do the same test, but this time run tcpdump this way so we capture packets on the LAN interface:

`tcpdump -p -s0 -i eth0 -w wireguard.pcap udp port 9003`

I'd also appreciate it if you verify your RasPi can "see" the broadcast packets when Roon is correctly working.   Running:

`tcpdump -i eth0 -s0 -w test.pcap udp port 9003`

Note that the first command has a `-p` to disable promiscuous mode, while the second command does not have that flag.

**Comment by fraf1** [comment]
Hi Aaron,

The devices in the network are:
RaspPi; 192.168.0.172
Roon core on iMac: 192.168.0.129

Here you can find the logs. First command (tcpdump -p) ran with udp-proxy-2020 running, second command (tcpdump without -p) ran with udp-proxy-2020 stopped

[logs_04.zip](https://github.com/synfinatic/udp-proxy-2020/files/5369248/logs_04.zip)

P.S.
On RaspPi I have:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.172  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::dea6:32ff:fe0e:3691  prefixlen 64  scopeid 0x20<link>
        ether ...  txqueuelen 1000  (Ethernet)
        RX packets 281359249  bytes 3499865556 (3.2 GiB)
        RX errors 10457  dropped 12811  overruns 0  frame 2
        TX packets 257710401  bytes 16703874 (15.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

On the iMac I have:

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=50b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV,CHANNEL_IO>
	ether ... 
	inet6 fe80::14e1:3cb3:84a:79c3%en0 prefixlen 64 secured scopeid 0x4 
	inet 192.168.0.129 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex,flow-control,energy-efficient-ethernet>)
	status: active

```

**Comment by synfinatic** [comment]
So a few of things:

1. I'm seeing a fair bit of broadcast traffic to 10.255.255.255 from 192.168.0.172.  It's in both pcap's and I'm trying to figure out why that is?  Do you have 10/8 configured anywhere?  I'm trying to figure out why that is happening because it's seems a little odd.  Doubly odd that the destination MAC address is 38:43:7d:a4:c9:c5 and not the broadcast address FF:FF:FF:FF:FF:FF.

2.In the first pcap (wireguard.pcap) udp-proxy-2020 is correctly forwarding the broadcast discovery packets from your phone, but there aren't any replies.  The packets look correctly formatted, but for some reason your Roon Core on the Mac isn't responding.

3. In the second pcap I don't see the UDP/9003 discovery from a device talking to your Roon Core on the Mac.  I think I probably should of been more clear that you need to make sure you exit the Roon app on your phone or whatever and then launch it.  If it was running in the background it won't re-discover.  Also, running the Roon app on the same machine as the Roon Core server software probably won't provide the info I'm looking for.

4. Can you confirm your phone can talk to your Mac over Wireguard normally?   Easiest is probably to connect the phone to the VPN and ping the phone from your Mac.

**Comment by fraf1** [comment]
Hi Aaron,

So, while VPN is enabled on the phone:
- from the phone I can ping the Mac (on 192.168.0.129)
- from the phone I can ping the Raspi (the last both on the 192.168.0.172 and on the 10.6.0.1 IP).
- from the Raspi I can ping the phone (on 10.6.0.2 IP)
- from the Mac I can ping the Raspi (on the 192.168.0.172 IP)
- from the Mac I cannot ping the phone (on the 10.6.0.2 IP)

I think the last point is the source of the problem...
I think there is something wrong in my network config and the Mac does not know where to route the packages for 10.6.0.x network.

Will investigate...

Thanks!
Francesco

**Comment by fraf1** [comment]
Ah ah!
If I connect the mac to wireguard as well, so it has the 10.6.0.5 IP as well, and I run udp-proxy-2020 on the RaspPi, Roon works from the phone!

Will try a bit more...

**Comment by synfinatic** [comment]
Sounds like you need to run: `route add -net 10.6.0.0/24 192.168.0.172` on your Mac.  You might also be able to get away with adding a route to 10.6.0.0/24 on your home router/firewall to your Pi.  It _should_ do ICMP Redirects to clients so they learn to use the RasPi in that case, but there is sometimes a difference between what the RFC's say and what computers actually do. :)

**Comment by fraf1** [comment]
Hi Aaron,

It took me a while to test it, but I finally managed to do it.
Adding the routing route in the Mac effectively seems to work, but I am seeing some drop-off (i.e. the music stops after a few seconds of a song and Roon says that there are issue with the data loading) that I do not have when the Mac is on VPN. So maybe there's a bit more, but to be honest keeping the Mac connected to the VPN is not a big issue.

Ah, of course, VPN alone would not be enough without udp-proxy-2020!

**Comment by synfinatic** [comment]
So you've got something going on with your networking if you're getting music stopping/cutting out.  RAAT uses TCP for transport for music and `udp-proxy-2020` isn't involved at all.  UDP is really only for discovery as far as I can tell.

I'm a little surprised that `udp-proxy-2020` is helping when your MAC is also connected to the VPN. I'd be curious to see what the output of the following commands on your RasPi when the phone & Mac are connected:

`ifconfig`
`netstat -rn`

As well as what the logs of `udp-proxy-2020` are when both are connected and you start the roon app on the phone for the first time.

**Comment by fraf1** [comment]
Hi Aaron,

I'm a bit surprised as well. When I installed and configured wireguard at first, I thought the same, if both devices are connected to the VPN, the roon client on the phone should find the roon core on the Mac, but this was not the case until your `udp-proxy-2020`.

```
root@rpi4:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.172  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::dea6:32ff:fe0e:3691  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:0e:36:91  txqueuelen 1000  (Ethernet)
        RX packets 325277485  bytes 1419302872 (1.3 GiB)
        RX errors 10583  dropped 12965  overruns 0  frame 2
        TX packets 293634387  bytes 616735464 (588.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 3524945  bytes 595696719 (568.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3524945  bytes 595696719 (568.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.6.0.1  netmask 255.255.255.0  destination 10.6.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 101877502  bytes 48085064928 (44.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 147001604  bytes 150085768556 (139.7 GiB)
        TX errors 312766  dropped 1434259 overruns 0  carrier 0  collisions 0

root@rpi4:~# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 eth0
10.6.0.0        0.0.0.0         255.255.255.0   U         0 0          0 wg0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0

```

Log both phone and mac on vpn:
[log_05.zip](https://github.com/synfinatic/udp-proxy-2020/files/5387577/log_05.zip)

Log phone on VPN only:
[log_06.zip](https://github.com/synfinatic/udp-proxy-2020/files/5387588/log_06.zip)

To be honest, it could even a problem with the mobile carrier. In the last two or three days I see very slow performances and low coverage at times, confirmed by people with the same carrier. Don't know, maybe they are changing the infrastructure for the 5G (I'm on 4G) and they reduce the bandwidth in the meantime.
Today at lunch I measured 80 Mpbs, but this evening, when I was testing Roon, I had only 2 or 3 Mbps, in the same place...

In this moment, Roon with phone on VPN and Mac not, is working fine. So it could really just be a temporary problem with my cell phone bandwidth, even if it does not explain why everything was working with both client and core on VPN, but it could have been just a matter of luck.

In this moment at my desk I have 13.6 Mbps in download from the phone, a couple of hours ago I had 1.18 Mbps in the same place, I had to go near a window to reach the whopping speed of 5.8... Home connection is 300 Mbps download / 30 upload, so that should not be the bottleneck.

**Comment by synfinatic** [comment]
Yeah, looking at the logs, I don't see any indication that packets from the phone are being sent to the Mac over the VPN- it's only being sent to the Mac over `eth0` which is expected/as designed.

I strongly believe you are correct- the problem with the music dropping has to do with the wireless signal from your phone to your mobile carrier.  Could be network congestion or other interference.  I know when I do my testing over OpenVPN I'm also using my mobile carrier data connection and occasionally experience the same, while local testing between different VLAN's never has this problem.

Anyways, sounds like this is working so I'll see about maybe a clean up and merge this to the `main` branch.  Thanks for testing!
