### ISSUE TITLE
str2pcap should just parse debug logs

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/udp-proxy-2020#36]
Rather than copy & pasting lines, just parse them.

**Comment by harshitashankar** [comment]
Can you add more information on this? I see contents being copied from inputfile to output file in `str2pcap/main.go`. What do you mean by "JUST" parsing? Do you want to remove the code that writes to outfile?

**Comment by synfinatic** [comment]
right now the --debug flag spits out the hex values of the packet.  Currently to use str2pcap someone has to copy and paste those values from the output and into a file which obviously sucks.  I believe the logger can output JSON which would make parsing the logs automatically pretty simple for str2pcap to do without requiring the user to copy  & paste.

**Comment by synfinatic** [comment]
no need now that we create pcap files
