### ISSUE TITLE
Add support for site-to-site OpenVPN tunnels

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/udp-proxy-2020#41]
We can't rely on udp-proxy-2020's auto-learn functionality with site-to-site VPN's because the client/initiator side must have it's packets forwarded over the point-to-point VPN tunnel before we can learn.  Ideally, we should use some kind of POSIX API call to figure out the IP address or something of the other end, but for initial testing purposes I guess we can just have the user specify an IP address?

**Comment by jarleler** [comment]
Hi, I tried setting things up to build it. I am on a Windows 10 machine. Set up Vagrant, running FreeBSD 11.2. I have checked out the code and trying to build it:

gmake freebsd

The error message I get is:
---------------
root@:/usr/home/vagrant/udp-proxy-2020/udp-proxy-2020 # gmake freebsd
/bin/sh: Please install VirtualBox: https://www.virtualbox.org: not found
gmake: *** [Makefile:161: .vagrant-check] Error 127
---------------

I installed all the VirtualBox alternatives i found with: pkg search virtualbox

Any clue?

**Comment by jarleler** [comment]
I might be one step closer. Have learned some more about Vagrant, so starting it with the Vagrantfile you provided now..

**Comment by jarleler** [comment]
Hm, actually I get the same error message as above. I think I need some help here... :-)

**Comment by synfinatic** [comment]
Here, use this: https://synfin.net/misc/udp-proxy-2020-0.0.7beta1-freebsd-amd64

**Comment by jarleler** [comment]
Thanks! I tested it now - seems to be working well!! :-) I confirmed with tcpdump that once I start it on the client-side the packages are sent out on the LAN-interface on the server side. I will be testing it more tomorrow, also to get confirmed that the application using the packages actually can make use of them as intended. Thanks again!

PS! Any chance you see what is wrong with the build issue I have?

Cheers, 
Jarle

**Comment by synfinatic** [comment]
Well you're running Windows 10 on your computer and launched FreeBSD in a VM (VMWare, etc?)  

uh, I have no idea... I pretty much hate FreeBSD at this point.  My dev platform is MacOS and I use Vagrant/VirtualBox to build the FreeBSD VM to build the binary for FreeBSD due to the dependency on libpcap and hence the requirement to use GCC for compiling the code (unlike most Go programs, udp-proxy-2020 can't easily be cross compiled using the Go compiler).

I hear Windows has some fancy Linux thing going on now (Have I mentioned the last time I really used Windows was like Win95??)    From there you probably can install vagrant & virtualbox and then just run `make freebsd`.  Or since you already have FreeBSD running, you can take a look at the https://github.com/synfinatic/udp-proxy-2020/blob/main/Vagrantfile and run those commands.

**Comment by synfinatic** [comment]
Also, I'd be curious if you could provide the output of `ifconfig <openvpn interface>` on either end of the tunnel (with the tunnel up).   Also if you have a pcap you'd be willing to share that would be helpful.  I'd like to avoid requiring people hard code the IP address in the cli arguments if possible, but I'm not 100% sure what the right way to go about it is.

**Comment by jarleler** [comment]
Yes, running Win10 with vagrant/virtualbox. The build issue was related to me trying to run "make freebsd" instead of just "gmake". Building worked well with "gmake". I will send ifconfig and pcap files ASAP.

**Comment by jarleler** [comment]
Client-side:
ovpnc2: flags=8151<UP,POINTOPOINT,RUNNING,PROMISC,MULTICAST> metric 0 mtu 1500
        options=80000<LINKSTATE>
        inet6 fe80::96c6:91ff:fe14:f244%ovpnc2 prefixlen 64 scopeid 0xa
        inet 10.51.10.2 --> 10.51.10.1 netmask 0xffffffff
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: tun openvpn
        Opened by PID 99153

Server-side:
ovpns1: flags=8151<UP,POINTOPOINT,RUNNING,PROMISC,MULTICAST> metric 0 mtu 1500
        options=80000<LINKSTATE>
        inet6 fe80::96c6:91ff:fe1c:4d06%ovpns1 prefixlen 64 scopeid 0x9
        inet 10.51.9.1 --> 10.51.9.2 netmask 0xffffffff
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: tun openvpn
        Opened by PID 28015
pcap-files attached in zip-file.

[udp-proxy_site_to_site_captures.zip](https://github.com/synfinatic/udp-proxy-2020/files/5628547/udp-proxy_site_to_site_captures.zip)

**Comment by jarleler** [comment]
If there are broadcasts from a host on the server-side LAN - will these packages be sent to the other side also, even with no fixed-ip specified? It looks like it works like that now (which is OK/good).

**Comment by synfinatic** [comment]
So to answer your question, the `--fixed-ip` argument basically is a hack around the learning feature in udp-proxy-2020 so it knows how to forward traffic on a PointToPoint interface like used by OpenVPN.  As you can see, the client and server sides of the OpenVPN tunnel are actually on different networks which is honestly kinda 'weird' but that's how OpenVPN works.  

Anyways, when the client tries talking to the server, the udp-proxy-2020 service on the server side automatically learns the client IP for 90 seconds by default.  You can override the the 90sec limit via the `--timeout` argument.  If both sides may initiate communications, then you can specify `--fixed-ip` on both ends.  Won't hurt anything.

Honestly, I think it probably doesn't really matter what IP address you use with the `--fixed-ip` option... OpenVPN tunnels are kinda dumb.
