### ISSUE TITLE
Compile version for UDM/UDMP

### ISSUE THREAD

**Issue by tiehfood** [synfinatic/udp-proxy-2020#43]
Could someone help me to compile a version for the UDM/UDMP, would be great. The version for the USG does not work

**Comment by synfinatic** [comment]
did you try the other Linux version?  If that doesn't work, you'll need to tell me more about the hardware in the UDM/UDMP since I don't own one.

**Comment by tiehfood** [comment]
On both linux versions I get the following error:
line 1: syntax error: unexpected word (expecting ")")

result of "uname -a" 
Linux UDM 4.1.37-v1.8.3.2949-494bdab #1 SMP aarch64 GNU/Linux

**Comment by tiehfood** [comment]
Great job so far, exactly the tool I was looking for 👍🏼

**Comment by synfinatic** [comment]
Oh, that's ARM.  I know someone has built it on a raspi, but I haven't built a cross-compile tool chain for that yet.

**Comment by tiehfood** [comment]
Should I then take a look at the "Dockerfile.arm64" file?

**Comment by synfinatic** [comment]
Yeah, the linux/arm support is there, just not in the last release.  Here's [a binary](https://synfin.net/misc/udp-proxy-2020-0.0.6-linux-arm64-static)

**Comment by tiehfood** [comment]
Great, thanks! I'll give it a try

**Comment by tiehfood** [comment]
Works great. I use OpenVPN to connect two subnets with a site-to-site tunnel. Running your tool on both endpoints enables Roon to successfully connect to the devices on the other end 👍.

**Comment by tiehfood** [comment]
Do you think it's possible to use your tool for redirecting mDNS traffic too?

**Comment by synfinatic** [comment]
There are existing tools for mDNS like Avahi: https://avahi.org  I don't know about the UDM(Pro), but the USG/USG-Pro support that.  Sadly Ubiquiti released the UDM series with an extremely limited feature set which is why I run pfSense now at home.

**Comment by tiehfood** [comment]
Like with Roon the problem with avahi and OpenVPNs tun0 interface is the missing multicast implementation. So I thought maybe your tool could be used to work around this too

**Comment by synfinatic** [comment]
Maybe?  you could definitely tell udp-proxy-2020 to listen on udp/5353 and see what happens.  I was under the impression that Avahi did some mDNS protocol decoding & modification, but honestly I've never really looked into how it works.  I know under pfSense, the Avahi config lets you pick OpenVPN tunnel interfaces as they do support multicast.

**Comment by tiehfood** [comment]
With mDNS: "Unable to decode packet from eth0: No decoder for layer type Dot1Q"

**Comment by synfinatic** [comment]
Oh, looks like you're seeing VLAN tagged frames on the non-tagged native interface.   Is it crashing or erroring out?  Because if it just ignores it and carries on with life that shouldn't be a problem 

That said, probably makes sense to open another ticket and carry on the conversation there if this is something important to you
