### ISSUE TITLE
pfsense startup instructions

### ISSUE THREAD

**Issue by mph88** [synfinatic/udp-proxy-2020#56]
Thanks for this program, it works great! However, I was having issues with the pfsense startup script instructions. Here is what I got to work properly on 2.5:

1. udp-proxy-2020.conf should be in /usr/local/etc/

2. startup rc script udp-proxy-2020 should be in /usr/local/etc/rc.d/; made executable with chmod +x

3.  /etc/rc.conf.local doesn't exist by default and will have to be created or copied from this repo. Unlike freebsd, the rc.conf file gets cleared at boot, so it's important to use rc.conf.local.

4. the freebsd-amd64 binary should be placed in /usr/local/bin; made executable with chmod +x

5. The rc script can't have the dashes in the variable name or a variable error is thrown; this means the start/stop/cleanup/status/commands need to be modified as well.

6. wget isn't installed on pfsense by default but fetch is. This was probably the easiest way to download the files from this repo to their proper directories over ssh.

**Comment by synfinatic** [comment]
Thanks for the feedback.  I've already done some of those things here: https://github.com/synfinatic/udp-proxy-2020/pull/55 but will update the PR soon!

As for copying files, yeah, I just use ssh.

**Comment by mph88** [comment]
Perfect! It's pretty comical that this program had to be written as roon and pfsense lack the functionality. Seems so simply in theory.

**Comment by synfinatic** [comment]
Yeah, I don't really blame pfSense for this... Roon is just well, being stupid in their design.  How hard would it to be for when discovery fails for you to have the option to enter the hostname or IP address of the Roon Core?  That would solve 99% of the use cases where people want to do this.

Anyways, I just updated the PR and hopefully improved the README instructions.  if you wouldn't mind taking a quick look and letting me know what you think, I'd appreciate it.

**Comment by mph88** [comment]
Oh I agree, it would be a relatively simple implementation and it would allow for easy remote access. Maybe there is some legacy device that's preventing them from implementing it?

Yes the PR looks good. I pushed it to the pfsense box using the clearer directions and everything worked just fine. I've gotten into the habit of using service instead of directly calling the rc script, but either works.

**Comment by synfinatic** [comment]
oh, i'm so *BSD stupid I didn't even know it had the `service` command like linux.   that's easier.  Thanks for the help!
