### ISSUE TITLE
Armv7 Release

### ISSUE THREAD

**Issue by acupofjose** [synfinatic/udp-proxy-2020#68]
Would love to try this out! I'm attempting to access PS Remote play via the internet behind a double NAT. So I'd like to do port forwarding through zerotier or tailscale on a intranet device that would relay the packets to the playstation and back. 

Unfortunately, I only have a raspberry pi to work with as my relay device. Any chance you could do an armv7 release?

**Comment by synfinatic** [comment]
hopefully this clarifies things: https://github.com/synfinatic/udp-proxy-2020/blob/main/README.md#what-binary-is-right-for-me

**Comment by acupofjose** [comment]
@synfinatic the Arm32 worked for me, that documentation helps a ton. Thanks so much!
