### ISSUE TITLE
No audio devices / zones found unless pfsense service is stoped and started

### ISSUE THREAD

**Issue by TTK-199837** [synfinatic/udp-proxy-2020#71]
Hey, 

Tkronic from the roon forums here. As the title says, roon does not find any audio zones / devices unless i stop and restart the service. After I have done this, the zones stay up and controllable until the device shuts down / disconnects from network. If I leave my desktop where I primarily listen to music at home on 24/7 it is not an issue. When I turn it off or suspend it, I need to access pfsense and stop and start the service. OpenVPN with my phone is not as convenient. I believe openVPN disconnects when the phone is idle / screen off for any significant amount of time. This means, every time I want to listen to Roon on my phone, i need to access pfsense and run the stop start commands. 

Note: the phone connects to my core (ROCK on a VM) just fine, it just does not see it as a playable / stream able audio device / zone. 

Please let me know what logs I can send, or additional information I can provide that can be of use. 

Thanks so much again.

**Comment by TTK-199837** [comment]
Step 2 Log:

[21.05.1-RELEASE][admin@pfsense.home]/root: udp-proxy-2020 --list-interfaces
Interface: igb1
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.1.1/24  Broadaddr: 192.168.1.255
	- IP: fe80::1:1/64
	- IP: 192.168.1.10/32  Broadaddr: 192.168.1.10

Interface: ix3
	- IP: fe80::290:bff:fea2:9d6c/64

Interface: igb1.8
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.8.1/24  Broadaddr: 192.168.8.255

Interface: lo0
	- IP: ::1/128
	- IP: fe80::1/64
	- IP: 127.0.0.1/8

Interface: igb1.21
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.21.1/24  Broadaddr: 192.168.21.255

Interface: igb1.200
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.200.1/24  Broadaddr: 192.168.200.255

Interface: igb1.500
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.50.1/24  Broadaddr: 192.168.50.255

Interface: igb0
	- IP: fe80::290:bff:fea2:9d67/64

Interface: ngeth0
	- IP: fe80::1293:97ff:fe0e:6f61/64
	- IP: 108.75.135.203/22  Broadaddr: 108.75.135.255

Interface: ovpnc1
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 10.15.0.3/16  PointToPoint: 10.15.0.1
	- IP: fdda:d0d0:cafe:1301::1001/64

Interface: ovpnc2
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 10.15.0.4/16  PointToPoint: 10.15.0.1
	- IP: fdda:d0d0:cafe:1301::1002/64

Interface: ovpns3
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 192.168.10.1/24  PointToPoint: 192.168.10.2

**Comment by TTK-199837** [comment]
Failure: Roon could connect, no audio devices found.

**Comment by TTK-199837** [comment]
pcaps... 

[igb1-2.zip](https://github.com/synfinatic/udp-proxy-2020/files/7449968/igb1-2.zip)

**Comment by synfinatic** [comment]
missing the logs?

**Comment by TTK-199837** [comment]
Sorry! Let me redo the process...

**Comment by synfinatic** [comment]
Doh.  If that's the case, if you can also run `ps auxww >processes.log` while it is running that would be great.

Right now, my _best_ guess is some other process is coming along and causing issues, but I have no idea what it might be.

**Comment by TTK-199837** [comment]
Sorry, I am a noob at all this, would the ps auxww >processes.log command be run in an ssh shell for my pfsense router?

**Comment by synfinatic** [comment]
Yep!  :)

**Comment by TTK-199837** [comment]
Alright :) ill give it a shot. I will start the udp-proxy-2020 --debug --interface igb1.21,igb1.200 --port 9003 --logfile udproxy.log command and then immediately start the  ps auxww >processes.log command in a separate terminal.

**Comment by TTK-199837** [comment]
OK Step 2 again!

[21.05.1-RELEASE][admin@pfsense.home]/root: service udp-proxy-2020 status
udp-proxy-2020 is not running.
[21.05.1-RELEASE][admin@pfsense.home]/root: udp-proxy-2020 --list-interfaces
Interface: igb1
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.1.1/24  Broadaddr: 192.168.1.255
	- IP: fe80::1:1/64
	- IP: 192.168.1.10/32  Broadaddr: 192.168.1.10

Interface: ovpnc1
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 10.15.0.9/16  PointToPoint: 10.15.0.1
	- IP: fdda:d0d0:cafe:1301::1007/64

Interface: igb1.21
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.21.1/24  Broadaddr: 192.168.21.255

Interface: lo0
	- IP: ::1/128
	- IP: fe80::1/64
	- IP: 127.0.0.1/8

Interface: ovpns3
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 192.168.10.1/24  PointToPoint: 192.168.10.2

Interface: igb1.8
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.8.1/24  Broadaddr: 192.168.8.255

Interface: igb1.200
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.200.1/24  Broadaddr: 192.168.200.255

Interface: igb1.500
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.50.1/24  Broadaddr: 192.168.50.255

Interface: igb0
	- IP: fe80::290:bff:fea2:9d67/64

Interface: ngeth0
	- IP: fe80::1293:97ff:fe0e:6f61/64
	- IP: 108.75.135.203/22  Broadaddr: 108.75.135.255

Interface: ovpnc2
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 10.15.0.4/16  PointToPoint: 10.15.0.1
	- IP: fdda:d0d0:cafe:1301::1002/64

Interface: ix3
	- IP: fe80::290:bff:fea2:9d6c/64

**Comment by TTK-199837** [comment]
Error this time: Roon Bridge was started, but this time, my iOS device was unable to see it as an audio device at anytime, even right after executing udp-proxy-2020, which normally works. Not sure if this is because of the delay from booting up the core on .200. Uploading pcaps and logs now.

**Comment by TTK-199837** [comment]
[try number 2.zip](https://github.com/synfinatic/udp-proxy-2020/files/7456444/try.number.2.zip)

**Comment by TTK-199837** [comment]
That zip should have everything... please let me know if I am missing something, I will be standing by for a while and can respond quickly.

**Comment by TTK-199837** [comment]
[I have to use roon on iOS to see / command Roon because I use linux as my primary desktop, and there is no GUI]

**Comment by synfinatic** [comment]
I see you're running Snort.  That will also be "sniffing" traffic on the wire.  I'm actually wondering if that is causing a problem (basically the two are fighting).  Can you stop snort and restart udp-proxy-2020 and see if that works better?

**Comment by TTK-199837** [comment]
Got it.

**Comment by TTK-199837** [comment]
No change with snort off. Service is running on pfsense, roonbridge I started and stopped multiple times, and iOS app started and closed multiple times. No audio zones found..

**Comment by synfinatic** [comment]
Bummer... I was really hoping that was it.  I'll look at the logs/etc more closely after work.

**Comment by TTK-199837** [comment]
Thanks man, I appreciate it a lot!

**Comment by synfinatic** [comment]
fyi, looks like you gave me the /var/log/udpproxy.log file?  Not the file created where you manually ran `udp-proxy-2020` in step 3.  I know that, because it has log entries from yesterday?

**Comment by TTK-199837** [comment]
[udproxy.zip](https://github.com/synfinatic/udp-proxy-2020/files/7456761/udproxy.zip)

**Comment by TTK-199837** [comment]
Not sure how I mess that up... is this one legit?

**Comment by TTK-199837** [comment]
this is the log right from root... which I thought i pulled haha

**Comment by synfinatic** [comment]
those are the same files?  the one I'm expecting should be much smaller

**Comment by TTK-199837** [comment]
They might be the same. I did not check. I took "udproxy.log" from /root from admin@pfsense.home... Did not go into /var/log/etc... is the file you need from root or from another location?

**Comment by TTK-199837** [comment]
I ran [21.05.1-RELEASE][admin@pfsense.home]/root: scp udproxy.log [to destination]

**Comment by TTK-199837** [comment]
I can rm -r that file and redo the process.... just let me know. Not sure whats going on to be honest.

**Comment by synfinatic** [comment]
sure delete the file and be sure to start `udp-proxy-2020` manually like I wrote it- don't use the startup script.

**Comment by TTK-199837** [comment]
I copy paste your commands every time ;) OK will redo

**Comment by TTK-199837** [comment]
(sure it is exactly the same as the last to times.. but)

Step 2 log:

[21.05.1-RELEASE][admin@pfsense.home]/root: udp-proxy-2020 --list-interfaces
Interface: igb0
	- IP: fe80::290:bff:fea2:9d67/64

Interface: ngeth0
	- IP: fe80::1293:97ff:fe0e:6f61/64
	- IP: 108.75.135.203/22  Broadaddr: 108.75.135.255

Interface: ovpnc1
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 10.15.0.9/16  PointToPoint: 10.15.0.1
	- IP: fdda:d0d0:cafe:1301::1007/64

Interface: ovpns3
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 192.168.10.1/24  PointToPoint: 192.168.10.2

Interface: igb1.200
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.200.1/24  Broadaddr: 192.168.200.255

Interface: igb1.500
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.50.1/24  Broadaddr: 192.168.50.255

Interface: igb1
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.1.1/24  Broadaddr: 192.168.1.255
	- IP: fe80::1:1/64
	- IP: 192.168.1.10/32  Broadaddr: 192.168.1.10

Interface: ovpnc2
	- IP: fe80::290:bff:fea2:9d67/64
	- IP: 10.15.0.4/16  PointToPoint: 10.15.0.1
	- IP: fdda:d0d0:cafe:1301::1002/64

Interface: ix3
	- IP: fe80::290:bff:fea2:9d6c/64

Interface: igb1.8
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.8.1/24  Broadaddr: 192.168.8.255

Interface: igb1.21
	- IP: fe80::290:bff:fea2:9d68/64
	- IP: 192.168.21.1/24  Broadaddr: 192.168.21.255

Interface: lo0
	- IP: ::1/128
	- IP: fe80::1/64
	- IP: 127.0.0.1/8

**Comment by TTK-199837** [comment]
[try 3.zip](https://github.com/synfinatic/udp-proxy-2020/files/7456895/try.3.zip)

**Comment by TTK-199837** [comment]
this time my phone was able to be seen as an audio zone initially, but not my roonbridge. After I quit the app, it was not available as an audio zone.

**Comment by synfinatic** [comment]
so just a FYI:

I looked at your pcap files which show the Roon discovery protocol and here is a quick analysis:

```
192.168.200.5 on igb1-21   10858
192.168.200.5 on igb1-200   10835
192.168.21.7 on igb1-21    5808
192.168.21.7 on igb1-200    5718
```

The last column is the total number of packets for that host/interface.  When udp-proxy-2020 is working correctly we would expect to see roughly the same number of packets for a given host on BOTH interfaces.  In this case, the numbers are very close which is good.

But, these numbers are VERY HIGH.  

Looking closer at the packet captures, I see that the first packets are sent by `192.168.200.5` which based on the contents of the packets and what you have told me is your Roon Core.  This is strange because the Roon Core typically only RESPONDS to requests from a Roon Client.   Now that is _probably_ because I had you restart the Core and it's just announcing itself onto the network.  So perhaps not that strange?

Turns out there is another Roon Client on igb1-21:

```
192.168.21.9 on igb1-21    1170
192.168.21.9 on igb1-200    1148
```

Okay, that sorta helps explain the Core talking out of turn, but it's still really odd.

The odd part is that when I sniff on my pfSense box and connect from a Roon Client on one VLAN to my Core on another VLAN, the total number of packets sent on udp/9003 between the two is **37**.  That's a lot fewer (multiple orders of magnitude!) then you have on your network.

So there seems to be far far far too many packets showing up on your network in a very short time.  

Honestly, I wonder if you have some kind of network loop on your network?  That or is another system running `udp-proxy-2020`?  Because either you have discovered a very unique bug in the Roon networking code causing it to flood these packets or you have something else causing it?

The other really odd thing is that roughly 50% of the packets being sent by your Core and two clients has a "time to live" (TTL) of 2.  Basically, I've only ever seen this value to be 64 for Roon packets.  No idea what is going on there, but this makes me think you have some other kind of software or something doing weird things?  No idea if you tried some other piece of software before `udp-proxy-2020` and it's still running?  (Basically the TTL usually starts at 64 and then is reduced by one for every "hop" on the internet.  So basically this indicates that Roon packets have made 62 "hops" (64-62 = 2) but that frankly sounds insane.)

Anyways... long story short, I don't know what is causing your problem.  Only that it is indeed super weird and that `udp-proxy-2020` seems to be working correctly.  Your issue seems to be something networking related, but I don't have enough context to say what for certain. 

You might try unplugging everything but your firewall to the internet and slowly add once device back (starting with the Roon Core and then your first Roon Client) and then figure out when things break and then debug from there.

**Comment by TTK-199837** [comment]
Thanks for the diagnostic. I will do as you suggested - shutdown and disconnect all devices involved and slowly bring them online. I will attempt to study your reply and try to learn what you are seeing and Troubleshoot on my own! Thanks a lot!

On Mon, Nov 1, 2021, at 6:02 PM, Aaron Turner wrote:
> 
> 
> so just a FYI:
> 
> I looked at your pcap files which show the Roon discovery protocol and here is a quick analysis:
> 
> `192.168.200.5 on igb1-21   10858
> 192.168.200.5 on igb1-200   10835
> 192.168.21.7 on igb1-21    5808
> 192.168.21.7 on igb1-200    5718
`
> The last column is the total number of packets for that host/interface. When udp-proxy-2020 is working correctly we would expect to see roughly the same number of packets for a given host on BOTH interfaces. In this case, the numbers are very close which is good.
> 
> But, these numbers are VERY HIGH.
> 
> Looking closer at the packet captures, I see that the first packets are sent by `192.168.200.5` which based on the contents of the packets and what you have told me is your Roon Core. This is strange because the Roon Core typically only RESPONDS to requests from a Roon Client. Now that is *probably* because I had you restart the Core and it's just announcing itself onto the network. So perhaps not that strange?
> 
> Turns out there is another Roon Client on igb1-21:
> 
> `192.168.21.9 on igb1-21    1170
> 192.168.21.9 on igb1-200    1148
`

**Comment by synfinatic** [comment]
looked at the code (been a while) and learned found that the best way to tell the difference between a packet sent by a host (Roon core or client) and `udp-proxy-2020` is looking at something called the UDP Header Checksum.  

Basically, udp-proxy-2020 takes a short cut and hard codes this value to `0` which is always valid.

```
igb1-21 with checksum = 0   17554
igb1-21 with checksum != 0     282

igb1-200 with checksum = 0   17532
igb1-200 with checksum != 0     169
```

Now that _is_ interesting.   udp-proxy-2020 is sending a LOT more packets than the Roon devices are.

Now, I'm assuming you're running the latest version of udp-proxy-2020???  

`udp-proxy-2020 --version`

Should report something like:

```
udp-proxy-2020 Version 0.0.7 -- Copyright 2020-2021 Aaron Turner
2e0813457a51c54062cdf763ffc8bd0ec0d78a01 (Unknown) [13 delta] built at 2021-05-23T21:24:04+0000
```

I'd expect the first line to match, but the 2nd line to be different.

If the above matches, can you do another test.  Basically just capture traffic on `igb1-200` like above, while the core is running, start a Roon Client and DO NOT run udp-proxy-2020 on your firewall.  I just want to see if the Core is talking with no expected clients on the network.

That would also help prove/disprove that there is something else funny going on your network.

**Comment by TTK-199837** [comment]
[21.05.1-RELEASE][admin@pfsense.home]/root: udp-proxy-2020 --version
udp-proxy-2020 Version 0.0.7 -- Copyright 2020-2021 Aaron Turner
308dbf04deedaf488950746532e1b83e42904850 (v0.0.7) built at 2021-05-23T21:46:38+0000

**Comment by TTK-199837** [comment]
So, just to be clear, I should run "tcpdump -i igb1.200 -s0 -w igb1-200.pcap udp port 9003" with core running + the client without udp-proxy-2020 running?

**Comment by synfinatic** [comment]
Yep, that would do it!

**Comment by TTK-199837** [comment]
[igb1-200.zip](https://github.com/synfinatic/udp-proxy-2020/files/7457543/igb1-200.zip)

**Comment by TTK-199837** [comment]
seems like a small file!

**Comment by synfinatic** [comment]
Well this seems to indicate that something is bridging your two networks:

<img width="1266" alt="Screen Shot 2021-11-01 at 8 07 32 PM" src="https://user-images.githubusercontent.com/1075352/139780647-f1af4436-234c-47ab-a761-585dc18c05a4.png">

Notice there is traffic from 192.168.200.5 (expected since you are sniffing in VLAN 200) and also 192.168.21.7 which is supposed to be on VLAN 21!

Looking at your previous pcaps from both igb1-21 and igb1-200, I see 192.168.21.7 on both networks and in both cases the UDP Checksum is not 0 which indicates that udp-proxy-2020 did not send the packet.  What is interesting is that the Source MAC Address on VLAN 21 indicates the network card was made by Apple, but on VLAN 200 the network card is made by/registered to a company called [Lanner Electronics](https://www.lannerinc.com).  

Not sure what device on your network that is, but that is probably the source of your troubles.

**Comment by TTK-199837** [comment]
Lanner I believe would be the pfsense SG-5100.

Apple would most likely be my iPhone

I also have a custom built PC running ubuntu on VLAN21, not sure how that would show up as far as MFG (but it has an ASUS motherboard). 

VLAN200 is an HP pc I am using as a server.... 

Don't know if that helps at all.

**Comment by synfinatic** [comment]
So your phone is running Roon and talking to the Roon core without udp-proxy-2020???

how is that happening?

**Comment by TTK-199837** [comment]
I have a firewall rule that allows all traffic from VLAN21 to VLAN200 and the reverse just for testing. 

And no, the phone did not communicate with core during that test. . .

**Comment by synfinatic** [comment]
Allowing them to talk is good.  But the pcap you gave me shows them talking.  Even if the Roon app isn't working correctly, they are talking.  You can see the traffic going both ways in the picture I uploaded.

**Comment by TTK-199837** [comment]
true...

**Comment by TTK-199837** [comment]
I think UDP-Proxy-2020 must be running in some way...

**Comment by TTK-199837** [comment]
[21.05.1-RELEASE][admin@pfsense.home]/root: service udp-proxy-2020 status
udp-proxy-2020 is not running.

**Comment by TTK-199837** [comment]
just ran this and lol my phone is playing music via roon right now

**Comment by TTK-199837** [comment]
anyway to check if pfsense has another instance of udp-proxy-2020 running?

**Comment by TTK-199837** [comment]
It is odd that my roonbridge is not getting picked up as an audio zone, but the iPhone is.

**Comment by synfinatic** [comment]
`service udp-proxy-2020 status` is not an 100% accurate way of detecting if it is running if you have something starting it outside of the script/etc.  This is better:

`pgrep -lf udp-proxy-2020`

If the service is running, you'd see something like:

```
22299 /usr/local/bin/udp-proxy-2020 --port 9003 --interface lagg0,lagg0.200,lagg0.500,ovpns2,ovpns6 --logfile /var/log/udp-proxy-2020.log
22158 daemon: /usr/local/bin/udp-proxy-2020[22299]
```

Note that the 2nd line typically only happens via the startup script.

**Comment by TTK-199837** [comment]
Nothing comes up when I run that!

[21.05.1-RELEASE][admin@pfsense.home]/root: pgrep -lf udp-proxy-2020
[21.05.1-RELEASE][admin@pfsense.home]/root:

**Comment by synfinatic** [comment]
Btw, I should mention it doesn't appear that udp-proxy-2020 is running since all the packets have a checksum.  So something else is going on.  Do you have any special firewall/NAT rules for udp/9003?  something else?

**Comment by TTK-199837** [comment]
![Screenshot from 2021-11-01 20-31-33](https://user-images.githubusercontent.com/55029898/139782631-af803866-8604-4973-a341-22313131cf97.png)

**Comment by TTK-199837** [comment]
Just took another packet capture haha and yea, they are talking wtf!

**Comment by synfinatic** [comment]
Well, you can try to force-quit Roon on your phone and restart it and see if it can find the Core again.   I'm guessing it won't.

The reality is that once the Client and Core are talking to each other like they are doing now, they don't need udp-proxy-2020 anymore.  It's only used for the initial discovery/broadcast packets.

**Comment by TTK-199837** [comment]
OK. ill give it a few more days and let you know if I find anything. Thanks again.

**Comment by synfinatic** [comment]
the only other thing I can think of that would cause odd behavior is if you have the IGMP Proxy enabled.

in the pfSense web admin: Services -> IGMP Proxy

If that is enabled, then it can cause weird behaviors with Roon/udp-proxy-2020.  Unfortunately the way Roon works, it's not really compatible with IGMP Proxies because every interface is an "upstream" interface and pfSense only allows one.

**Comment by TTK-199837** [comment]
Not running the IGMP proxy for anything…

**Comment by TTK-199837** [comment]
After resetting my phone, like you predicted, no communication.

**Comment by synfinatic** [comment]
So I have another working theory that the reason we're seeing tens of thousands of packets when there should be only a few hundred is that udp-proxy-2020 is "seeing" the packets it is sending out and thinks they are arriving on the interface and need to be sent again.

In theory, this shouldn't happen because I make a specific call to _only_ look for inbound packets.  But Perhaps there is a bug in the network card or driver on that specific hardware and that API call isn't working as intended.  

So this version of code adds another way of filtering out the packets that are being sent so they're not re-sent again (and again, and again for infinity).

So give it a try and let me know?  https://synfin.net/misc/udp-proxy-2020-0.0.8-freebsd-amd64

**Comment by TTK-199837** [comment]
Ok. I will attempt this later tonight (hopefully) and get back to you! Thanks!

**Comment by TTK-199837** [comment]
OK, so... 

My iOS devices are working flawlessly now. They are on two different VLANs and connect instantly and automatically (even now, the next day). My roonbridge service on Linux did not show up as an audio zone. Roon on windows connects to the core but does not show up as an audio zone. 

When using OpenVPN however, my iOS phone can connect and manipulate, but does not show up as an audio zone.

**Comment by synfinatic** [comment]
So iOS is "fixed" but Linux and Windows is still broken?  Or did that used to work and is worse now?  Ignoring the OpenVPN for now, where are Windows and Linux on the network compared to the iOS devices?

I assume you've tried restarting Roon on all the devices, so maybe you can do the network capture like above, but only for Windows or Linux?

**Comment by TTK-199837** [comment]
Linux roonbridge was able to be used as an audio zone before, and was somewhat more reliable compared to the iOS devices (but still not perfect, had to run another UDP-PROXY-2020 instance to get a connection). 

Windows and Linux are on VLAN21, the same as one iOS device that works perfect. 

Yes, Windows and Linux were both fully restarted during this testing.

I will try a network capture right now.

**Comment by TTK-199837** [comment]
WOW. I am an idiot. I did not check the firewall settings on my Linux PC, and it was default deny incoming... after turning the firewall off, the computer connected as an audio zone. I will have to see if my windows has a similar setup. wow... OK, looks like it is working for now. I took logs if you would like to see them... but at this point I will try connecting and disconnection, rebooting to make sure it is solid. Sorry if I wasted your time! Thanks again.

**Comment by synfinatic** [comment]
Well that's good to hear.  Sounds like your phone on OpenVPN is still an issue though?

**Comment by TTK-199837** [comment]
Yes, OpenVPN is not working still, but, after rebooting Linux and ensuring the roonbridge service was running and firewall still off, no connection to core again. Very odd.

**Comment by synfinatic** [comment]
If you've got time right now, happy to jump on Discord to chat?  Probably easier than this.  Just email me at <my username> at gmail dot com and I'll send you an invite

**Comment by TTK-199837** [comment]
[igb1-21.zip](https://github.com/synfinatic/udp-proxy-2020/files/7493084/igb1-21.zip)
[udproxy.zip](https://github.com/synfinatic/udp-proxy-2020/files/7493085/udproxy.zip)

**Comment by TTK-199837** [comment]
[igb1-200.zip](https://github.com/synfinatic/udp-proxy-2020/files/7493104/igb1-200.zip)
