### ISSUE TITLE
Can we run this proxy somewhere else than the router?

### ISSUE THREAD

**Issue by jvican** [synfinatic/udp-proxy-2020#81]
Great project, thanks for putting the time into this. I'm using a Peplink router and have limited access to it via SSH, meaning I can't install any package on my own. I still need to use this project, though, because I want to forward broadcast messages between my home network and my Wireguard network (whose service runs in an instance inside my homelab).

Does udp-proxy work if I run it inside the instance which also runs Wireguard instead of my router? I was trying to get it to work recently and failed, and was wondering if it was possible at all.

**Comment by synfinatic** [comment]
Not enough information to say with 100% confidence, but yes, in this case you should run it on the same system as Wireguard.  Because Wireguard servers are routers. :)

**Comment by jvican** [comment]
Thanks for the reply, that was my impression too. I will need to look at this again and see where I was failing to get it configured.

**Comment by jvican** [comment]
Tried configuring udp-proxy-2020 again without luck. The logs seem to detect some traffic:

```
DEBU[0055]/build/udp-proxy-2020/cmd/listen.go:132 main.(*Listen).handlePackets() handlePackets(wg0) ticker                    
DEBU[0055]/build/udp-proxy-2020/cmd/listen.go:132 main.(*Listen).handlePackets() handlePackets(eth0) ticker
```

`--fixed-ip` doesn't work in my particular scenario. It's weird because Wireguard does work and can access internal services such as web servers running inside my home network, but doesn't look like broadcast messages are being forwarded. My instance is a container running inside Proxmox, so not sure if it has anything to do with the way I set up the bridge there, but don't think so.

@synfinatic I was wondering, could you share some logs of successfully forwarded broadcast messages? I was hoping maybe that would clarify if udp-proxy-2020 is working in the first place. In my case, I'm trying to set this up for Roon and running the proxy with: `/usr/local/bin/udp-proxy-2020 --debug --interface eth0,wg0 --port 9003 --cachettl 300`.
