### ISSUE TITLE
Docker image synfinatic/udp-proxy-2020:latest does not exist

### ISSUE THREAD

**Issue by margua** [synfinatic/udp-proxy-2020#83]
Whe I try to run the startup script /mnt/data/on_boot.d/40-udp-proxy-2020.sh on my UNifi UDM-Pro it ends with this error: 

Trying to pull docker.io/synfinatic/udp-proxy-2020...
  manifest unknown: manifest unknown

The problem is that the docker container image is referenced as synfinatic/udp-proxy-2020:latest in the script but this label does not exist. If i change the label to :v0.0.8 the image is available and the container starts successfully.

**Comment by synfinatic** [comment]
try now.

**Comment by margua** [comment]
> try now.

It works like a charm! Thanks :)
