### ISSUE TITLE
Downlaod of Docker image fails

### ISSUE THREAD

**Issue by Brendianer** [synfinatic/udp-proxy-2020#92]
Dear all
I am trying to install the docker image on my Synology.
After choosing "latest" the downlaod alwas fails.
What could be the reason?

**Comment by synfinatic** [comment]
oh, looks like I forgot to update that after the v0.0.11 release.  should work now!

**Comment by synfinatic** [comment]
well, `--debug` isn't a valid flag anymore.  You can look in the logs and it will tell you what is going on:
<img width="1458" alt="Screen Shot 2022-04-27 at 8 38 39 AM" src="https://user-images.githubusercontent.com/1075352/165557089-7d057323-435a-48ba-b4b7-076ca16f6893.png">

**Comment by Brendianer** [comment]
Fatal error to specify two interfaces.
I put eth0 and tun0.
It says eth0 is not configured.

**Comment by synfinatic** [comment]
I dunno... is it?  I don't use eth0 personally.  You'll want to ssh into your NAS and run `ifconfig` and see what the correct interface is.

**Comment by Brendianer** [comment]
I got this:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/23482834/165561705-1fe1c946-df1d-46e0-b3cd-58e1ab9a1643.png">
So i put in bond0 and tun0. No further error message but the container always restarts.

**Comment by synfinatic** [comment]
you have to remove the `-l` flag.  When you specify that it lists the interfaces and then exits.

**Comment by synfinatic** [comment]
https://github.com/synfinatic/udp-proxy-2020/blob/main/README.md#when-should-i-use---no-listen

**Comment by synfinatic** [comment]
Sounds like this is working now?  If so, then I'll close this ticket.
