### ISSUE TITLE
udp-proxy-2020 on Raspberry

### ISSUE THREAD

**Issue by Brendianer** [synfinatic/udp-proxy-2020#96]
Dear all
I installed udp-proxy-2020 on a Raspberry 4 (hopefuly correctly) according the guide.
If I ask for the status I get an error like this:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/23482834/166938724-cd7c978f-9143-43f0-a49d-e11c6b9552c5.png">

What do I have to do?
P.S. How can I exit the window after receicving this message?
Thanks a lot.

**Comment by Brendianer** [comment]
No idea what that means

![image](https://user-images.githubusercontent.com/23482834/167029951-3324d033-cf44-4223-8bd8-a448e5fc6fe4.png)
Conf file:
![image](https://user-images.githubusercontent.com/23482834/167030192-8d41f310-4749-48bc-88bf-5662f1f1ded9.png)

**Comment by synfinatic** [comment]
seems like the error is in your `/lib/systemd/system/udp-proxy-2020.service` file... what are the contents?

**Comment by Brendianer** [comment]
[Unit]
Description=UDP Proxy 20202
Documentation=https://github.com/synfinatic/udp-proxy-2020
Wants=network-online.target
After=network-online.target

[Service]
EnvironmentFile=/etc/udp-proxy-2020.conf
User=root
Group=root
Type=simple
Restart=on-failure
ExecStart=/usr/bin/udp-proxy-2020 $ARGS

LimitNOFILE=10000
TimeoutStopSec=20
UMask=0027

[Install]
WantedBy=multi-user.target

**Comment by synfinatic** [comment]
okay, looks like the problem is the `\` on the end of the `ARGS` line.  it should only be there if you have actual args there.

**Comment by Brendianer** [comment]
Took it off.
The error persists:

![image](https://user-images.githubusercontent.com/23482834/167033703-6fa06a7f-84d2-47a5-9e7e-2ba9231d99cd.png)

**Comment by synfinatic** [comment]
Sorry, the output of that command only confirms it didn't start..  the logs are what gives the hints.  Can you look in the logs and paste in the most recent?

**Comment by Brendianer** [comment]
Here we go

![image](https://user-images.githubusercontent.com/23482834/167034190-afb35011-675e-49a1-bdfd-19fc7250b4cc.png)

Thank you.

**Comment by synfinatic** [comment]
Nope, those are the same logs from last time.  notice the timestamps are the same?

**Comment by Brendianer** [comment]
I noticed. But I only get this output. Maybe I am stupid. But I rebooted and did everything again. Still only with that timestamp.

**Comment by synfinatic** [comment]
you can use the `spacebar` to scroll to the next page or `shift-g` to go to the end.  `g` to go back to the top.  `j` and `k` to go down/up one line.

**Comment by Brendianer** [comment]
Aha! that looks much better

![image](https://user-images.githubusercontent.com/23482834/167035483-e89cd6d0-2956-46d4-b228-90829c975a6c.png)

**Comment by synfinatic** [comment]
`permission denied`   means file permissions are wrong.  most likely you forgot to mark the binary as executable: `chmod 755 /usr/bin/udp-proxy-2020`

**Comment by Brendianer** [comment]
Runs now without error. Thank you so much!!!
Did config remotly.
Will check tomorrow when back in the office.

**Comment by Brendianer** [comment]
So I tried now to see whether it starts on reboot.
I get an error message like that

<img width="869" alt="image" src="https://user-images.githubusercontent.com/23482834/167085373-18bca899-0670-430e-bac9-048683949018.png">

If I start it manually (I have to enter ther password for my user) it works.

P.S. How can I delete the journal/logfile to have a better overview?

**Comment by Brendianer** [comment]
Ok I tried. No functionality.
Roon core on my home network. Synology running udp-roxy-2020. Nor error
Other network Raspberry running udp-proxy-2020.
Both location connected with OpenVPN.
Port 1194 forwarded on both netoworks to the server running OpenVPN.
Must I forward any other port e.g. 9003?
Thanks a lot.

**Comment by synfinatic** [comment]
okay, sounds like you're doing a site-to-site VPN.   That is what we call "advanced" :)

I really need a basic network diagram to understand how you have things deployed.  Doesn't have to be fancy- draw it on a piece of paper, take a picture with your phone and upload it if you want.  

Key things to show:
 1. What device and where is it that is your Roon core  
 2. What device and where is it that you are  running the Roon client
 3. What devices are running udp-proxy-2020
 4. What devices are running OpenVPN
 5. What devices (like a firewall??) are in between the above list

For Roon, udp-proxy-2020 only needs to forward udp/9003.

**Comment by synfinatic** [comment]
I can't speak to Sonus specifically since I don't know how Roon supports that and I don't own one to test/find out.  Ie: does it use the normal Roon discovery protocol or something else?  If something else, then maybe or maybe not.

I just use Roon on my phone/laptop while traveling.   But yeah, that is the general idea.
