### ISSUE TITLE
forward of multicast packets

### ISSUE THREAD

**Issue by mnaiman** [synfinatic/udp-proxy-2020#98]
Is it possible to add support to forward to other interfaces multicast packets instead of broadcast?

Eg. DLNA devices are sending UDP packets to port 1900 239.255.255.250:1900 with notification of their location ip address.
If this packet would be able to forwarded to other interfaces they would know how to connect.

Thanks

**Comment by synfinatic** [comment]
Have you tried it?  As long as the multicast packets are being sent to the device running udp-proxy-2020 it should work.  There is no filter that limits it to broadcast packets- which is why it works on OpenVPN tunnels which don't support broadcast.

**Comment by mnaiman** [comment]
Yes I did. 
In wireshark, I see broadcast packets are forwarded. But multicast packets are not.
I have one physical interface, and 4 VLAN created on this interface, could it be issue?
Thanks

**Comment by synfinatic** [comment]
"depends" on the NIC/driver.  udp-proxy-2020 doesn't know how to decode 802.1Q VLAN tags.  My suggestion would be to use a physical NIC for each network.
